### ISSUE TITLE
Choice of target allele with truncated query seq

### ISSUE THREAD

**Issue by pmenzel** [iferres/MLSTar#13]
Hi,

I noticed an issue in the blast processing function that occurs when the query sequence contains only a subsequence of a target that matches equally well to multiple allele sequences in the blast database. Then MLSTar will pick the first line of the blast result as the allele.

In the below example, the 5'-end of the query contig contains 401nt that match identically to the 3'-end of multiple allele sequences and MLSTar will return allele number 98 for this locus.
```
 sample  locus    qseqid   sseqid nident pident mismatch  gaps length qstart  qend sstart  send  slen bitscore qseq                                                                                   
1 MySample EFAU004… Contig_…     98    401    100        0     0    401      1   401    725  1125  1125      741 AACAATTTCTCGCACTTTTGAACCAAAATAAAAAGAAAGACCTTTTT…
2 MySample EFAU004… Contig_…     96    401    100        0     0    401      1   401    725  1125  1125      741 AACAATTTCTCGCACTTTTGAACCAAAATAAAAAGAAAGACCTTTTT…
3 MySample EFAU004… Contig_…     95    401    100        0     0    401      1   401    725  1125  1125      741 AACAATTTCTCGCACTTTTGAACCAAAATAAAAAGAAAGACCTTTTT…
4 MySample EFAU004… Contig_…     94    401    100        0     0    401      1   401    725  1125  1125      741 AACAATTTCTCGCACTTTTGAACCAAAATAAAAAGAAAGACCTTTTT…
5 MySample EFAU004… Contig_…     93    401    100        0     0    401      1   401    725  1125  1125      741 AACAATTTCTCGCACTTTTGAACCAAAATAAAAAGAAAGACCTTTTT…
```
I think it is related to this calculation of `blastRes$scov`, which uses query coordinates and should probably just use the subject length:
https://github.com/iferres/MLSTar/blob/ef8dcf4c3bb2b0de5014ba9e2604b5b667e58b0e/R/blastInternals.R#L155

It is an edge case and probably does not happen often, but I suggest it should be handled as an NA allele instead of using just the first allele sequence?

**Comment by iferres** [comment]
Hi @pmenzel , thanks for reporting this bug. It is certainly expected what you mention. I'll try to fix it as soon as possible.

**Comment by iferres** [comment]
Sorry for the delay, I have made some changes and pushed them to branch `develop`. Please reinstall MLSTar, try it and let me know if this fix corrected the issue, so I can merge them to `master`. I didn't have the time to check it so your feedback will be very welcome.
```{r}
devtools::install_github('iferres/MLSTar', ref = 'develop')
```
Thanks!
