### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by nweerasu** [iferres/MLSTar#18]
Hello!

Is there any intention of expanding this package to have Windows compatibility?

Thanks!
Nimalka

**Comment by iferres** [comment]
Hi @nweerasu , sorry but it is not in my plan. I don't have a Windows machine where to test whether it works or doesn't. Since MLSTar depends on external software (blast+ toolkit) it is difficult to set up an automatic test to check everything runs ok.

**Comment by nweerasu** [comment]
Ok, ty!
