### ISSUE TITLE
doMLST() Error on R Console

### ISSUE THREAD

**Issue by haruosuz** [iferres/MLSTar#3]
In R version 3.3.3 on Mac OS X Mavericks 10.9.5,
using the doMLST() function by pasting into the console printed Error:
```
Running BLASTN...Error in strsplit(db, "/") : non-character argument
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
```

It ran without any problem in R version 3.5.0 on macOS High Sierra 10.13.4.

**Comment by iferres** [comment]
Thanks Haruo. It seems to be a OS problem. I'll update the requirements to make notice of this.
Thanks for reporting this issue.
