### ISSUE TITLE
fdir doMLST bug

### ISSUE THREAD

**Issue by JFsanchezherrero** [iferres/MLSTar#6]
Dear @iferres, 

I have seen that if I provide full path for `fdir` within the `doMLST` function I get a folder and subfolders generated in the directory where I call the function.
Instead of getting the folder I provide:

`fdir = "/home/jsanchez/DATA/MLSTar/example2_test"`

I get the folder generated in other path. 
`/home/jsanchez/DATA/MLSTar/home/jsanchez/DATA/MLSTar/example2_test`

I have checked your code and seems ok so I guess if you have any suggestion.

I guess the problem is because it is iteratively generated by dir.create and it generates a folder for each '/' idenfitied. I wonder if you are using this option (recursive=TRUE) for some reason.

I also noticed that if I use Rstudio this does not occur but if I run the same code using Rscript it occurs. I have checked with sessionInfo() and in both examples I am using the same modules, R versions etc. 

I wonder if you have any thought or solution. Also, as a possible solution I guess if you could discard stopping the function if fdir already exists or setting recursive to False.

Thank you very much
Jose F Sanchez

**Comment by iferres** [comment]
Hi, I think I had this problem time ago, and I didn't find a solution at the moment. I don't know if it has anything to do with R's defaults, or what.. It seems to behave differently depending on the platform you're using. May be is a good idea to set `recursive = FALSE` to make the code more robust.

Since you have been recently digging in the code and actively using MLSTar (I don't, really :P), I was wondering if you could try this solution by forking the repo and making a pull request if you can solve it. I'd really appreciate that. If you don't feel confident enough just let me know and I will try to fix it as soon as possible.

Thank you again for giving a try to MLSTar, I'll waiting for any comments. I'll keep this issue open.
Bests

**Comment by JFsanchezherrero** [comment]
Hi,
I have to admit I am not very skilled in R in terms of developing my own packages. 

I dont know for sure if I fork and update the repo if then I would be able to test and debug it as: I wouldnt know how to install it from git repo and then I am not sure how to differenciate this installation from my own. 

I know I should learn how to do this but I am more focused on other languages and I only employ R for plotting and other purposes using small scripts and/or CRAN modules.

I have been checking your code and I think that basically it would to add to file quickMLST.R:
https://github.com/iferres/MLSTar/blob/master/R/quickMLST.R

in line 96, the argument recursive=FALSE:
 `dir.create(fdir, recursive=FALSE)`

As I said, I guess there are no more dependencies but I am not sure 100%.

As I said on other issue, I am working on a pipeline for the identification of strains and I would like to use MLSTar for that purpose among other softwares. We are also implementing a module where when new strain or new alleles are identified, the database is populated in order to better identify future sample. I would share my code when available if you are interested.

Thank you very much,

**Comment by iferres** [comment]
Hi, don't worry. It was a lazy request on my part. I have made the suggested changes on branch `develop`. Just remember to install that specific branch:
```r
devtools::install_github('iferres/MLSTar', ref = 'develop')
```
Keep me informed about this issue, if that change could fix the problem.

I will be glad to see your work when available. 
Bests!!

**Comment by JFsanchezherrero** [comment]
I am afraid it doesn't work. It still creates the home/and/many/subfolders in the working directory.
I have checked I have downloaded the proper developer version using the git commit id.

I am going to try to fork your repo, installing it using devtools, test it and fix it. I would try to set if folder already exists print a message but do not stop. It might be useful if you provide the whole path within another pipeline but you should bare in mind to specify it in the documentation for future users.

**Comment by JFsanchezherrero** [comment]
Ok. That is strange.

I forked your repo, created a developer branch, added a warning message if folder exists, installed it in my computer, ran same code as before and: 
1) I got the message I included if I previously create folder: 
```
Warning message:
In doMLST(infiles = genomes, write = "new", fdir = nameDir, schemeFastas = schemeFastas_list,:
  /home/jsanchez/DATA/MLSTar/example2_test/ already exists. Continuing anyway...
```
2) I also got the home/subfolders created in that directory so I am afraid, I dont know what is going on at all.
`/home/jsanchez/DATA/MLSTar/home/jsanchez/DATA/MLSTar/example2_test`

**Comment by JFsanchezherrero** [comment]
Ok. I quit. I have been trying several things using different parameters but I am afraid that is it. I can not sort it our but I guess I have found a solution, for me.

I would sort it out by setting the working directory when I call R and passing for `fdir` the name of the folder to create. Instead of providing a unique a unique argument to my script with fdir absolute path, I would provided the working directory and the name.

Best solution, no debugging, no need to keep on trying. 

But I have added a fix in your code, I have set recursive FALSE and showWarnings TRUE for dir.create and I have generate a warning and not a stop if the folder already exists. 

```
 if(!dir.exists(fdir)){
      #dont normalize path because in following steps directories are created
      # recursively.
      dir.create(fdir, showWarnings=TRUE, recursive=FALSE)
    }else{
      warning(paste0(fdir, ' already exists. Continuing anyway...'))
    }

```

It might be appopiate if users controls that. As I said before, you should change documentation if finally merging my changes from the pull request I generated #7 

Thank you very much

**Comment by iferres** [comment]
Hi. I cannot explain that behavior neither.. but I'm glad you could find a workaround. I can't `setwd()` inside the function because it could create some other issues for other users, and because is not a very best practice to do that, but if you plan to use the software internally in your organization I guess it will patch the problem successfully, so :+1: . 

I'll check the PR now, thanks a lot!
